### ISSUE TITLE
[DesignGaia2019] 4.2 評価実験を書く

### ISSUE THREAD

**Issue by Aono082** [ehimetakahashilab/papers#17]
## WHY
10月1日ルネサス提出のため

## WHAT
- 毎サイクルのFFにおけるCOPベースの可制御性を出す
- 毎サイクルのFFにおけるHybrid TPIのメトリクスを出す
- 可制御性とメトリクスで相関係数を出す

**Comment by MaineK00n** [comment]
前置き
- FFの可観測性ALL1の話
- Hybrid TPIを時間展開回路に対して実行したときにどう対応しているか

**Comment by MaineK00n** [comment]
https://github.com/ehimetakahashilab/papers/issues/17#issuecomment-529857068 は
こちら（#19）で対応

**Comment by Aono082** [comment]
初めに、サイクルを経て可制御性が極端に低く(高く)なるFFに注目
そのFFのCcを見て、故障検出能力とFFが固定値になる現象を説明

こういったケースがいくつあるか(FF全体の割合)を表にまとめる
閾値はCcの中央値とか全体の幾つとか

**Comment by MaineK00n** [comment]
> 初めに、サイクルを経て可制御性が極端に低く(高く)なるFFに注目

tglproの1サイクル目と5サイクル目の差分が大きいFFをソート

**Comment by Aono082** [comment]
>そのFFのCcを見て、故障検出能力とFFが固定値になる現象を説明

- 説明の仕方
可制御性が0か1に極端に偏っているFFに注目
そのFFのbかBに注目
もし、偏っている値と逆の値が要求されていたのならば
そのFFは故障検出低下の原因になる。
